# SPDX-FileCopyrightText: 2026 James Harton
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  CI:
    uses: beam-bots/.github/.github/workflows/docs-ci.yml@588b8730cc97a9f070bbd62d3a1e432ed2afc550 # main
