# SPDX-FileCopyrightText: 2026 James Harton
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  CI:
    uses: beam-bots/.github/.github/workflows/docs-ci.yml@9d53897810ee791c17a6a51f70dc07e3db6e28d5 # main
