# SPDX-FileCopyrightText: 2026 James Harton
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  CI:
    uses: beam-bots/.github/.github/workflows/docs-ci.yml@b978bb2af8d00a21a295c4ad40c929c8e29a3d69 # main
